services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      GKFEED_ADDRESS: ":8086"
      GKFEED_DB_PATH: "/data/db.sqlite"
    volumes:
      - ~/.local/share/gkfeed/data:/data
    restart: always
