package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"sync"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

var (
	databaseMu sync.RWMutex
	database   *sql.DB
)

func Configure(databaseURL string) error {
	if databaseURL == "" {
		return errors.New("database URL is empty")
	}

	pool, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return fmt.Errorf("open PostgreSQL database: %w", err)
	}
	pool.SetMaxOpenConns(25)
	pool.SetMaxIdleConns(5)
	pool.SetConnMaxLifetime(30 * time.Minute)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := pool.PingContext(ctx); err != nil {
		pool.Close()
		return fmt.Errorf("ping PostgreSQL database: %w", err)
	}

	databaseMu.Lock()
	previous := database
	database = pool
	databaseMu.Unlock()
	if previous != nil {
		_ = previous.Close()
	}
	return nil
}

func Close() error {
	databaseMu.Lock()
	pool := database
	database = nil
	databaseMu.Unlock()
	if pool == nil {
		return nil
	}
	return pool.Close()
}

func RunMigrations() error {
	if err := InitCoreSchema(); err != nil {
		return err
	}
	if err := MigratePasswords(); err != nil {
		return err
	}
	if err := InitWebAuthnSchema(); err != nil {
		return err
	}
	if err := InitRefreshTokenSchema(); err != nil {
		return err
	}
	return nil
}

func InitCoreSchema() error {
	database, err := getDB()
	if err != nil {
		return err
	}
	schema := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT,
			hashed_password TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS feed (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title TEXT,
			url TEXT,
			type TEXT,
			user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
		)`,
		`CREATE TABLE IF NOT EXISTS item (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			feed_id INTEGER REFERENCES feed(id) ON DELETE CASCADE,
			title TEXT,
			text TEXT,
			date TIMESTAMPTZ,
			link TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS deleted_items (
			user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
			item_id INTEGER REFERENCES item(id) ON DELETE CASCADE,
			PRIMARY KEY (user_id, item_id)
		)`,
		"CREATE INDEX IF NOT EXISTS feed_user_id_idx ON feed(user_id)",
		"CREATE INDEX IF NOT EXISTS item_feed_id_id_idx ON item(feed_id, id DESC)",
	}
	for _, statement := range schema {
		if _, err := database.Exec(statement); err != nil {
			return err
		}
	}
	return nil
}

func getDB() (*sql.DB, error) {
	databaseMu.RLock()
	pool := database
	databaseMu.RUnlock()
	if pool == nil {
		return nil, errors.New("database is not configured")
	}
	return pool, nil
}
